In [1]:
import numpy as np
import pandas as pd


In [2]:
df=pd.read_csv('data1/dataset.csv')


In [3]:
df.head()

Country   Age   Salary Purchased
0    FRANCE  44.0  72000.0        NO
1     SPAIN  27.0  48000.0       YES
2  GERAMANY  30.0  54000.0        NO
3     SPAIN  38.0  51000.0        NO
4   GERMANY  40.0      NaN       YES

In [4]:
print(df)

    Country   Age   Salary Purchased
0    FRANCE  44.0  72000.0        NO
1     SPAIN  27.0  48000.0       YES
2  GERAMANY  30.0  54000.0        NO
3     SPAIN  38.0  51000.0        NO
4   GERMANY  40.0      NaN       YES
5    FRANCE  35.0  58000.0       YES
6     SPAIN   NaN  52000.0        NO
7    FRANCE  48.0  60000.0       YES
8   GERMANY  50.0  67000.0        NO
9    FRANCE  37.0  83000.0       YES


In [6]:
X=df.iloc[:,:-1].values #locate indexes, all rows, 
Y=df.iloc[:,-1].values


In [7]:
print(X)
print(Y)

[['FRANCE' 44.0 72000.0]
 ['SPAIN' 27.0 48000.0]
 ['GERAMANY' 30.0 54000.0]
 ['SPAIN' 38.0 51000.0]
 ['GERMANY' 40.0 nan]
 ['FRANCE' 35.0 58000.0]
 ['SPAIN' nan 52000.0]
 ['FRANCE' 48.0 60000.0]
 ['GERMANY' 50.0 67000.0]
 ['FRANCE' 37.0 83000.0]]
['NO' 'YES' 'NO' 'NO' 'YES' 'YES' 'NO' 'YES' 'NO' 'YES']


In [8]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:,1:3])#numerical values
X[:,1:3]=imputer.transform(X[:,1:3])


In [9]:
print(X)

[['FRANCE' 44.0 72000.0]
 ['SPAIN' 27.0 48000.0]
 ['GERAMANY' 30.0 54000.0]
 ['SPAIN' 38.0 51000.0]
 ['GERMANY' 40.0 60555.555555555555]
 ['FRANCE' 35.0 58000.0]
 ['SPAIN' 38.77777777777778 52000.0]
 ['FRANCE' 48.0 60000.0]
 ['GERMANY' 50.0 67000.0]
 ['FRANCE' 37.0 83000.0]]


In [11]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[0])],remainder='passthrough')
X=np.array(ct.fit_transform(X))

In [12]:
print(X)

[[1.0 0.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 0.0 30.0 54000.0]
 [0.0 0.0 0.0 1.0 38.0 51000.0]
 [0.0 0.0 1.0 0.0 40.0 60555.555555555555]
 [1.0 0.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 0.0 48.0 60000.0]
 [0.0 0.0 1.0 0.0 50.0 67000.0]
 [1.0 0.0 0.0 0.0 37.0 83000.0]]


In [13]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
Y=le.fit_transform(Y)

In [14]:
print(Y)

[0 1 0 0 1 1 0 1 0 1]


In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test, Y_train, Y_test= train_test_split(X,Y,test_size=2,random_state=1)

In [16]:
print(X_train)

[[0.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 0.0 1.0 0.0 40.0 60555.555555555555]
 [1.0 0.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 0.0 1.0 38.0 51000.0]
 [0.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 0.0 48.0 60000.0]
 [0.0 0.0 1.0 0.0 50.0 67000.0]
 [1.0 0.0 0.0 0.0 35.0 58000.0]]


In [17]:
print(X_test)

[[0.0 1.0 0.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 0.0 37.0 83000.0]]


In [18]:
print(Y_test)

[0 1]


In [19]:
print(Y_train)

[0 1 0 0 1 1 0 1]


In [20]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
X_train[:,3:] = sc.fit_transform(X_train[:,3:])
X_test[:,3:] = sc.fit_transform(X_test[:,3:])


In [22]:
print(X_train)

[[0.0 0.0 0.0 1.2909944487358056 -0.19159184384578545 -0.8571443036070149]
 [0.0 0.0 1.0 -0.7745966692414834 -0.014117293757057777
  0.2591366499277019]
 [1.0 0.0 0.0 -0.7745966692414834 0.566708506533324 1.7523436397208947]
 [0.0 0.0 0.0 1.2909944487358056 -0.30453019390224867 -0.9876187007734103]
 [0.0 0.0 0.0 1.2909944487358056 -1.9018011447007988 -1.3790418922725967]
 [1.0 0.0 0.0 -0.7745966692414834 1.1475343068237058 0.18665087372414899]
 [0.0 0.0 1.0 -0.7745966692414834 1.4379472069688968 1.0999716538889173]
 [1.0 0.0 0.0 -0.7745966692414834 -0.7401495441200351
  -0.07429792060864197]]


In [24]:
print(X_test)

[[0.0 1.0 0.0 0.0 -1.0 -1.0]
 [1.0 0.0 0.0 0.0 1.0 1.0]]
